"""FlipCoin Python SDK — prediction markets on Base."""

from .async_client import AsyncFlipCoin
from .client import FlipCoin
from .models import (
    ApprovalDetail,
    ApprovalStatus,
    AuditLogEntry,
    AuditLogResponse,
    BatchMarketResult,
    BatchResult,
    ConfigResponse,
    ContractsInfo,
    CreateMarketResult,
    DepositInfo,
    DepositResult,
    ExploreResponse,
    FeedEvent,
    FeedResponse,
    FeesInfo,
    Fill,
    FlipCoinError,
    HistoryPointOHLC,
    HistoryPointRaw,
    LimitsInfo,
    LmsrPrices,
    LmsrState,
    Market,
    MarketHistoryResponse,
    MarketPerformance,
    MarketState,
    Order,
    OrderResult,
    Pagination,
    PerformanceResponse,
    PingFees,
    PingResponse,
    PlatformInfo,
    Position,
    Quote,
    SlippageCurve,
    SlippageCurveEntry,
    SSEEvent,
    TradeResult,
    ValidateResult,
    ValidationIssue,
    Webhook,
    WebhookCreateResult,
)
from .utils import idempotency_key, raw_to_usdc, usdc_to_raw

__version__ = "0.1.0"

__all__ = [
    # Clients
    "FlipCoin",
    "AsyncFlipCoin",
    # Error
    "FlipCoinError",
    # Helpers
    "usdc_to_raw",
    "raw_to_usdc",
    "idempotency_key",
    # Models
    "ApprovalDetail",
    "ApprovalStatus",
    "AuditLogEntry",
    "AuditLogResponse",
    "BatchMarketResult",
    "BatchResult",
    "ConfigResponse",
    "ContractsInfo",
    "CreateMarketResult",
    "DepositInfo",
    "DepositResult",
    "ExploreResponse",
    "FeedEvent",
    "FeedResponse",
    "FeesInfo",
    "Fill",
    "HistoryPointOHLC",
    "HistoryPointRaw",
    "LimitsInfo",
    "LmsrPrices",
    "LmsrState",
    "Market",
    "MarketHistoryResponse",
    "MarketPerformance",
    "MarketState",
    "Order",
    "OrderResult",
    "Pagination",
    "PerformanceResponse",
    "PingFees",
    "PingResponse",
    "PlatformInfo",
    "Position",
    "Quote",
    "SlippageCurve",
    "SlippageCurveEntry",
    "SSEEvent",
    "TradeResult",
    "ValidateResult",
    "ValidationIssue",
    "Webhook",
    "WebhookCreateResult",
]
